<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!--<link rel="stylesheet" href="http://localhost:8899/cursos/barcelonaactiva/sprint3/to-do/web/stylesheets/styles.css">-->
    <? require_once '../header.php'; ?>
</head>
<body>
    <h1>LOGIN 200</h1>
	<?php echo $this->content(); ?>
</body>
</html>